### ISSUE TITLE
Crash during bossfight

### ISSUE THREAD

**Issue by appgurueu** [regulus79/regulus_mtgamejam_2023#1]
```
2023-12-22 15:16:04: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'regulus_mobs' in callback luaentity_Step(): .../games/regulus_mtgamejam_2023/mods/regulus_mobs/boss.lua:191: attempt to index a nil value
2023-12-22 15:16:04: ERROR[Main]: stack traceback:
2023-12-22 15:16:04: ERROR[Main]: 	.../games/regulus_mtgamejam_2023/mods/regulus_mobs/boss.lua:191: in function 'func'
```

I think the boss was touching me, but I'm not sure.

**Comment by Wuzzy2** [comment]
I also got a crash during bossfight:

```
AsyncErr: Lua: Runtime error from mod 'regulus_mobs' in callback luaentity_Step(): .../games/regulus_mtgamejam_2023/mods/regulus_mobs/boss.lua:240: attempt to index a nil value
stack traceback:
	.../games/regulus_mtgamejam_2023/mods/regulus_mobs/boss.lua:240: in function <.../games/regulus_mtgamejam_2023/mods/regulus_mobs/boss.lua:224>
```

I think my crash happened when I hit the boss. But I already hit the boss many times before, so maybe the boss was about to die?

After the crash, I could restart the game as normal and fight the boss again; this time I could defeat the boss successfully and complete the game.

**Comment by regulus79** [comment]
I got this bug multiple times during beta-testing, but unfortunately I am unsure what is causing the problem. It could be due to an entity (e.g. the projectiles) being deleted before on_step is finally called?
I had previously
```
(In the function on_step)

        if moveresult.collides and self and self.object and self.object:get_velocity() then
            for _,collision in pairs(moveresult.collisions) do
                if collision.type=="object" and collision.object:is_player() then
                    collision.object:punch(
                        self.object,
                        nil,
                        {
                            damage_groups={
                                fleshy=1,
                            }
                        },
                        self.object:get_velocity():normalize() <----- line 191, where the LMD's error is happening. Wuzzy's error on line 240 is very similar, just for the secondary boss projectile
                    )
                    self.object:remove()
...
```

It would appear that one of the things being indexed is nil; however, in the `if` statement above, I have already made sure that `self`, `self.object`, and `self.object:get_velocity()` all exist.

At least the game is still continueable after the error happens. Unless I can find out what is causing the bug, I'm not sure if I will be able to fix it :(

**Comment by appgurueu** [comment]
I think I see the issue. You iterate over the collisions, of which there can be multiple. In particular, if the player is close, the entity may collide with the same player multiple times in one step, or it may collide with a node, then with the player. After punching the player, or after colliding with a node, you remove the object, so it becomes invalid and its velocity becomes `nil`. In the next iteration, this triggers the error. The checks don't guard against this because they are outside of the loop.

I've PR'd a fix: Simply `return` as soon as you have removed the object. The guards then become obsolete.

**Comment by regulus79** [comment]
Thank you so much! I would never had realized that the for loop over the collisions might have more than one element.
