### ISSUE TITLE
Various warnings

### ISSUE THREAD

**Issue by appgurueu** [regulus79/regulus_mtgamejam_2023#2]
Mostly deprecation warnings related to `use_texture_alpha`, `initial_properties`, etc.; all should be pretty easy to fix (as a modder, I usually have `chat_log_level = warning` so that I see these during development).

**Comment by regulus79** [comment]
Ah, I did not realize that those warnings actually existed (I usually launch minetest through the icon, not the terminal)

I have just pushed a couple of commits to fix the warnings. Obviously, these will not be included in any contentdb releases until after the jam ends.

**Comment by regulus79** [comment]
Ah wait, I only tested it on 5.7.0. Perhaps there are some more warnings on 5.7.8 which I am not seeing...
I will be upgrading to 5.8.0 presumably sometime soon, so perhaps I will fix those warnings in the near future.

**Comment by Warr1024** [comment]
Worth checking out `szutil_logtrace` in szutilpack.  Install and enable it, and then you can set `/logtrace warn` to get all warning+ messages in your in-game chat stream.

**Comment by regulus79** [comment]
Alright, I think I have finally fixed all of the warning messages. I'll go ahead and close this issue.

**Comment by appgurueu** [comment]
Yay! :tada:
