### ISSUE TITLE
Wand does not work if player has been deleted but not auth

### ISSUE THREAD

**Issue by Warr1024** [regulus79/regulus_mtgamejam_2023#7]
The player's wand is being set to "fly" if the player does not have a last login time, but players whose data has been deleted (e.g. via /remove_player) will not have a "powerup" state set anymore (meta was deleted) but will still have a last login time.  You should probably just be setting the default powerup state based on whether or not the player has a stored powerup state, rather than on whether their auth has previously been used.

**Comment by regulus79** [comment]
Hopefully fixed with https://github.com/regulus79/regulus_mtgamejam_2023/commit/c2b833cdf7e7c9fa52ca81f3b55b3f11d8c76612
